# ----------------------------------------------
# Example macro file for the DmpSimu
# ----------------------------------------------
# Author(s): Xin Wu 
# Revised: Fan Rui Rui	2013-8-14
# Revised: Xin Wu	2013-9-24
#   - set ouput file name
#   - switch to use Fabio's generator by setting /gun/sourceGen 1 
# ----------------------------------------------

/root/RootFile DmpSimu_Electron_100GeV

#
# Sets some default verbose
#
/control/verbose 2
/control/saveHistory
/run/verbose 1
/tracking/storeTrajectory 2
#/tracking/verbose 1

/gun/sourceGen 1
/gun/sourceType 1

/gps/particle e- 
# the following two lines are equivalent
#/gps/ene/type Mono 
/gun/spectrumType 0
/gps/ene/mono 100 GeV

#/stk/thicknessThickW 1 mm
#/payload/update

# run 10 events
/run/beamOn 10


