# ----------------------------------------------
# Example macro file for the DmpSimulation
# ----------------------------------------------
# Authors: Xin Wu 
#         
# ----------------------------------------------

/root/RootFile DmpSimu_Proton_power_sphere
/root/CalEcut -1 MeV

/control/verbose 2
/control/saveHistory
/run/verbose 1
/tracking/storeTrajectory 2
#/tracking/verbose 1

#/run/initialize

/gun/sourceGen 1 
/gun/sourceType 1 
/gun/spectrumType 2


/gps/particle proton
/gps/ene/min 500 MeV
/gps/ene/max 150 GeV

# run
/run/beamOn 1000


