# ----------------------------------------------
# Example macro file for the DmpSimu
# ----------------------------------------------
# Author(s): Xin Wu 
# Revised: Fan Rui Rui	2013-8-14
# Revised: Xin Wu	2013-9-24
#   - test macro to produce the generation debug ntuple of Fabio 
# ----------------------------------------------

/root/GenDebug true
/root/RootFile DmpGen

#
# Sets some default verbose
#
/control/verbose 2
/control/saveHistory
/run/verbose 1
/tracking/storeTrajectory 2
#/tracking/verbose 1

#/gun/sourceGen true
/gun/sourceGen false

/run/initialize

/gps/particle proton

# run 10 events
/run/beamOn 10


